spring:
  redis:
    #  Redis数据库索引（默认为0）
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000ms

    # 集群模式
    cluster:
      # 集群信息
      nodes: 192.168.211.211:7001,192.168.211.211:7002,192.168.211.211:7003,192.168.211.211:7004,192.168.211.211:7005,192.168.211.211:7006
      # 默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
      max-redirects: 5
